image:
  file: .gitpod.Dockerfile
ports:
- port: 3000
tasks:
- before: gem install tmuxinator
- init: bundle install --path vendor/bundle && ./bin/rails db:setup && cd ember && yarn install && npm install -g ember-cli
- command: tmuxinator
