image:
  file: .gitpod.Dockerfile
ports:
- port: 3000
tasks:
- before: gem install tmuxinator
- init: bundle install --path vendor/bundle && ./bin/rails ember:install ember:compile
- command: tmuxinator
