name: rails

windows:
- editor:
    layout: main-horizontal
    panes:
      - nvim
      - 
- server:
    layout: even-vertical
    panes:
      - ./binrails s
      - ./bin/rails c
      -
- git:
    layout: main-horizontal
    panes:
      - lazygit
      -
